### ISSUE TITLE
RPIOS - Debian version 12 (bookworm) support

### ISSUE THREAD

**Issue by sairuk** [retronas/retronas#366]
Created to track issue, testing on Deb 12 based RPIOS

Work already done: https://github.com/danmons/retronas/issues/345

Testing of branch: main

**Comment by sairuk** [comment]
Installation: OK
Launch: OK
Set User/Group: OK
Relaunch OK

**Comment by sairuk** [comment]
Installing Items: Broken

```
ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
Press [Enter] to continue...
```

we need to manually set LC_ALL, this is a known issue and requires a fix a the tooling level, we can work around this

**Comment by sairuk** [comment]
Installers (they just need to run to completion here, not fail)

Samba: OK
Netatalk 2: FAILED
```
dependency errors
```
Netatalk 3: OK
EtherDFS: OK
lighthttpd: OK
proftpd: OK
tftpd-hpa: OK
OpenSSH: OK
telnet: OK
NFS: OK
TFNS: OK
pygopherd: OK
3DS QR Codes: Failed
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error while linking: [Errno 2] No such file or directory: b'/data/retronas/3ds/cia' -> b'/data/retronas/roms/nintendo/3ds/cia'", "path": "/data/retronas/roms/nintendo/3ds/cia"}
```
Samba for PS2: OK
Playstation 3: OK
Samba for MiSTer: OK
Samba for X360: OK
Samba for Batocera: OK
Samba for RecalBox: OK
Samba for Emuelec: OK
fenir-ode-webserver: OK
xlink-kai: OK
gogrepo: OK
ROM Import: OK
FSP server: OK
Sabretools: OK
DiscImageCreator: OK
Samba for Amiga: OK
Syncthing: OK
Cockpit: OK
WebOne proxy: OK
Bitorrent: OK
aria2: OK
megatools: OK
apfs-fuse: OK
hb-store-cdn: OK
zterm: OK
atdpro: OK
miniterm: OK
dreampi: OK
ethflopd: OK
mc: FAILED
ytree: FAILED  
far2l: FAILED
ntp: FAILED
```
dependency error libnetfilter
```
WaybackProxy: OK

**Comment by sairuk** [comment]
these worked once deps from dreampi were resovled

Netatalk 2: OK
mc: OK
ytree: OK
far2l: OK
ntp: OK

**Comment by sairuk** [comment]
hdparm: OK
tcpser: OK
laptop-ao: OK
webui: OK
xboxmanager: OK
netlink: OK
kermit: FAILED
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Path /etc/inetd.conf does not exist !", "rc": 257}
```
nabu: OK
dexdrive: OK
open-iscsi: FAILED
```
ERROR! The requested handler 'open-iscsi - Restart service' was not found in either the main handlers list nor in the listening handlers list
```
linux-gadgets: OK
UPDDB: OK

**Comment by sairuk** [comment]
**ondevice menu**

ucon64: OK
extract-xiso: OK
hdl-dump: OK
nbd-client: OK
pfsshell: OK
cue2pops: OK
pi1541: OK

**Comment by sairuk** [comment]
kermit moved to a systemd service

**Comment by sairuk** [comment]
went through the last lot of playbooks to see gather facts, i can't see anything overly concerning with deb12 support so people can try and see how it goes

**Comment by aminta** [comment]
Current deluge 2.0.3-4 on bookworn make BitTorrent installable but not working, see: https://forum.deluge-torrent.org/viewtopic.php?t=56545

**Comment by sairuk** [comment]
thanks have added an opt-in updater to version 2.12 from debian testing

**Comment by aminta** [comment]
@sairuk where I can find this updater?

**Comment by aminta** [comment]
Ok, tried in branch "testing", unfortunately I get still errors:

```
November 8, 2023
11:46 PM
Started deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:46 PM
deluge-web.service: Consumed 2.783s CPU time.
systemd
11:46 PM
Stopped deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:46 PM
deluge-web.service: Scheduled restart job, restart counter is at 45.
systemd
11:46 PM
deluge-web.service: Consumed 2.783s CPU time.
systemd
11:46 PM
deluge-web.service: Failed with result 'exit-code'.
systemd
11:46 PM
deluge-web.service: Main process exited, code=exited, status=1/FAILURE
systemd
11:46 PM
TypeError: cannot unpack non-iterable NoneType object
deluge-web
11:46 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:46 PM
username, password = get_localhost_auth()
deluge-web
11:46 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 31, in default_hostlist
deluge-web
11:46 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:46 PM
default_hostlist(),
deluge-web
11:46 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 104, in __init__
deluge-web
11:46 PM
^^^^^^^^^^
deluge-web
11:46 PM
self.hostlist = HostList()
deluge-web
11:46 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/json_api.py", line 380, in __init__
deluge-web
11:46 PM
^^^^^^^^
deluge-web
11:46 PM
self.web_api = WebApi()
deluge-web
11:46 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/server.py", line 691, in __init__
deluge-web
11:46 PM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deluge-web
11:46 PM
self.__server = server.DelugeWeb(options=self.options)
deluge-web
11:46 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/web.py", line 70, in start
deluge-web
11:46 PM
web.start()
deluge-web
11:46 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/__init__.py", line 6, in start
deluge-web
11:46 PM
^^^^^^^
deluge-web
11:46 PM
sys.exit(start())
deluge-web
11:46 PM
File "/usr/bin/deluge-web", line 8, in <module>
deluge-web
11:46 PM
Traceback (most recent call last):
deluge-web
11:46 PM
Started deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:46 PM
deluge-web.service: Consumed 2.744s CPU time.
systemd
11:46 PM
Stopped deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:46 PM
deluge-web.service: Scheduled restart job, restart counter is at 44.
systemd
11:46 PM
deluge-web.service: Consumed 2.744s CPU time.
systemd
11:46 PM
deluge-web.service: Failed with result 'exit-code'.
systemd
11:46 PM
deluge-web.service: Main process exited, code=exited, status=1/FAILURE
systemd
11:45 PM
TypeError: cannot unpack non-iterable NoneType object
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
username, password = get_localhost_auth()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 31, in default_hostlist
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
default_hostlist(),
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 104, in __init__
deluge-web
11:45 PM
^^^^^^^^^^
deluge-web
11:45 PM
self.hostlist = HostList()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/json_api.py", line 380, in __init__
deluge-web
11:45 PM
^^^^^^^^
deluge-web
11:45 PM
self.web_api = WebApi()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/server.py", line 691, in __init__
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
self.__server = server.DelugeWeb(options=self.options)
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/web.py", line 70, in start
deluge-web
11:45 PM
web.start()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/__init__.py", line 6, in start
deluge-web
11:45 PM
^^^^^^^
deluge-web
11:45 PM
sys.exit(start())
deluge-web
11:45 PM
File "/usr/bin/deluge-web", line 8, in <module>
deluge-web
11:45 PM
Traceback (most recent call last):
deluge-web
11:45 PM
Started deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Consumed 2.883s CPU time.
systemd
11:45 PM
Stopped deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Scheduled restart job, restart counter is at 43.
systemd
11:45 PM
deluge-web.service: Consumed 2.883s CPU time.
systemd
11:45 PM
deluge-web.service: Failed with result 'exit-code'.
systemd
11:45 PM
deluge-web.service: Main process exited, code=exited, status=1/FAILURE
systemd
11:45 PM
TypeError: cannot unpack non-iterable NoneType object
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
username, password = get_localhost_auth()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 31, in default_hostlist
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
default_hostlist(),
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 104, in __init__
deluge-web
11:45 PM
^^^^^^^^^^
deluge-web
11:45 PM
self.hostlist = HostList()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/json_api.py", line 380, in __init__
deluge-web
11:45 PM
^^^^^^^^
deluge-web
11:45 PM
self.web_api = WebApi()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/server.py", line 691, in __init__
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
self.__server = server.DelugeWeb(options=self.options)
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/web.py", line 70, in start
deluge-web
11:45 PM
web.start()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/__init__.py", line 6, in start
deluge-web
11:45 PM
^^^^^^^
deluge-web
11:45 PM
sys.exit(start())
deluge-web
11:45 PM
File "/usr/bin/deluge-web", line 8, in <module>
deluge-web
11:45 PM
Traceback (most recent call last):
deluge-web
11:45 PM
Started deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Consumed 2.835s CPU time.
systemd
11:45 PM
Stopped deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Scheduled restart job, restart counter is at 42.
systemd
11:45 PM
deluge-web.service: Consumed 2.835s CPU time.
systemd
11:45 PM
deluge-web.service: Failed with result 'exit-code'.
systemd
11:45 PM
deluge-web.service: Main process exited, code=exited, status=1/FAILURE
systemd
11:45 PM
TypeError: cannot unpack non-iterable NoneType object
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
username, password = get_localhost_auth()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 31, in default_hostlist
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
default_hostlist(),
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 104, in __init__
deluge-web
11:45 PM
^^^^^^^^^^
deluge-web
11:45 PM
self.hostlist = HostList()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/json_api.py", line 380, in __init__
deluge-web
11:45 PM
^^^^^^^^
deluge-web
11:45 PM
self.web_api = WebApi()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/server.py", line 691, in __init__
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
self.__server = server.DelugeWeb(options=self.options)
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/web.py", line 70, in start
deluge-web
11:45 PM
web.start()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/__init__.py", line 6, in start
deluge-web
11:45 PM
^^^^^^^
deluge-web
11:45 PM
sys.exit(start())
deluge-web
11:45 PM
File "/usr/bin/deluge-web", line 8, in <module>
deluge-web
11:45 PM
Traceback (most recent call last):
deluge-web
11:45 PM
Started deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Consumed 2.066s CPU time.
systemd
11:45 PM
Stopped deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Scheduled restart job, restart counter is at 41.
systemd
11:45 PM
deluge-web.service: Consumed 2.066s CPU time.
systemd
11:45 PM
deluge-web.service: Failed with result 'exit-code'.
systemd
11:45 PM
deluge-web.service: Main process exited, code=exited, status=1/FAILURE
systemd
11:45 PM
TypeError: cannot unpack non-iterable NoneType object
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
username, password = get_localhost_auth()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 31, in default_hostlist
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
default_hostlist(),
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 104, in __init__
deluge-web
11:45 PM
^^^^^^^^^^
deluge-web
11:45 PM
self.hostlist = HostList()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/json_api.py", line 380, in __init__
deluge-web
11:45 PM
^^^^^^^^
deluge-web
11:45 PM
self.web_api = WebApi()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/server.py", line 691, in __init__
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
self.__server = server.DelugeWeb(options=self.options)
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/web.py", line 70, in start
deluge-web
11:45 PM
web.start()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/__init__.py", line 6, in start
deluge-web
11:45 PM
^^^^^^^
deluge-web
11:45 PM
sys.exit(start())
deluge-web
11:45 PM
File "/usr/bin/deluge-web", line 8, in <module>
deluge-web
11:45 PM
Traceback (most recent call last):
deluge-web
11:45 PM
Started deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Consumed 2.055s CPU time.
systemd
11:45 PM
Stopped deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Scheduled restart job, restart counter is at 40.
systemd
11:45 PM
deluge-web.service: Consumed 2.055s CPU time.
systemd
11:45 PM
deluge-web.service: Failed with result 'exit-code'.
systemd
11:45 PM
deluge-web.service: Main process exited, code=exited, status=1/FAILURE
systemd
11:45 PM
TypeError: cannot unpack non-iterable NoneType object
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
username, password = get_localhost_auth()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 31, in default_hostlist
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
default_hostlist(),
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/hostlist.py", line 104, in __init__
deluge-web
11:45 PM
^^^^^^^^^^
deluge-web
11:45 PM
self.hostlist = HostList()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/json_api.py", line 380, in __init__
deluge-web
11:45 PM
^^^^^^^^
deluge-web
11:45 PM
self.web_api = WebApi()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/server.py", line 691, in __init__
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
self.__server = server.DelugeWeb(options=self.options)
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/web.py", line 70, in start
deluge-web
11:45 PM
web.start()
deluge-web
11:45 PM
File "/usr/lib/python3/dist-packages/deluge/ui/web/__init__.py", line 6, in start
deluge-web
11:45 PM
^^^^^^^
deluge-web
11:45 PM
sys.exit(start())
deluge-web
11:45 PM
File "/usr/bin/deluge-web", line 8, in <module>
deluge-web
11:45 PM
Traceback (most recent call last):
deluge-web
11:45 PM
Started deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Consumed 2.052s CPU time.
systemd
11:45 PM
Stopped deluge-web.service - Deluge Bittorrent Client Web Interface.
systemd
11:45 PM
deluge-web.service: Scheduled restart job, restart counter is at 39.
systemd
11:45 PM
deluge-web.service: Consumed 2.052s CPU time.
systemd
11:45 PM
deluge-web.service: Failed with result 'exit-code'.
systemd
11:45 PM
deluge-web.service: Main process exited, code=exited, status=1/FAILURE
systemd
11:45 PM
TypeError: cannot unpack non-iterable NoneType object
deluge-web
11:45 PM
^^^^^^^^^^^^^^^^^^
deluge-web
11:45 PM
username, password = get_localhost_auth()
deluge-web
11:45 PM
```

**Comment by sairuk** [comment]
i do not see this behavior on deb12, i did however push some perms fixes that needed to be done after the updated packages were installed

**Comment by aminta** [comment]
@sairuk I've pulled your permissions fixes, now the service doesn't return errors but if I try to connect to deluge web ui on 8112  port it goes in timeout...

**Comment by sairuk** [comment]
pip has an exception handler in bookworm which we need to work around

we can remove `/usr/lib/python3*/EXTERNALLY-MANAGED` so we don't have to handle multiple command lines across distros
